// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BaseballAPI
{
    public partial class Team
    {
        public int TeamId { get; set; }
        public string TeamName { get; set; }
        public string City { get; set; }
        public string League { get; set; }
        public int Wins { get; set; }
        public int Losses { get; set; }
        public string TeamMascot { get; set; }
    }
}