// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BaseballAPI.Data
{
    [Table("Players")]
    public partial class Player
    {
        [Key]
        public int PlayerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        [ForeignKey("TeamId")]
        public int TeamId { get; set; }
        public Team Team { get; set; }
        public double BattingAverage { get; set; }
        public int HomeRuns { get; set; }
        public int Rbis { get; set; }
        public string Position { get; set; }
    }
}