// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BaseballAPI.Data
{
    [Table("TeamsTest")]
    public partial class Team
    {
        [Key]
        public int TeamId { get; set; }
        public string TeamName { get; set; }
        public string City { get; set; }
        public string League { get; set; }
        public int Wins { get; set; }
        public int Losses { get; set; }
        public string TeamMascot { get; set; }

        [ForeignKey("TeamId")]
        public List<Player> Players { get; set; }
    }
}